# Generated by Django 2.2 on 2020-12-30 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_news', '0005_auto_20201225_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=30, verbose_name='Телефон')),
                ('city', models.CharField(default='', max_length=30, verbose_name='Город')),
                ('verification', models.BooleanField(choices=[(False, 'Не пройдена'), (True, 'Пройдена')], default='False', verbose_name='Верификация')),
                ('news_count', models.IntegerField(default=0, verbose_name='Новостей опубликовано')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'profiles',
            },
        ),
    ]
