# Generated by Django 2.2 on 2020-12-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_auto_20201231_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=30, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='is_approved',
            field=models.BooleanField(choices=[(False, 'Не одобрена'), (True, 'Одобрена')], default=False, verbose_name='Одобрение'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='news', to='app_news.Tags', verbose_name='Теги'),
        ),
    ]
