# Generated by Django 2.2 on 2020-12-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0008_auto_20201231_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='news',
            field=models.ManyToManyField(default=None, related_name='tags', to='app_news.News', verbose_name='Новости'),
        ),
    ]
