# Generated by Django 2.2 on 2021-01-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0009_auto_20201231_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('verify', 'Может верифицировать'),), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
