# Generated by Django 2.2 on 2021-01-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0010_auto_20210103_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'permissions': (('approve', 'Может одобрять'),), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
