# Generated by Django 2.2 on 2021-01-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_auto_20210103_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'permissions': (('approve_news', 'Может одобрять'),), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('verify_profile', 'Может верифицировать'),), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
