# Generated by Django 2.2 on 2021-01-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0013_auto_20210104_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'permissions': (('approve_news', 'Может одобрять'),), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
