# Generated by Django 2.2 on 2021-01-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='on_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='', max_length=3000, verbose_name='О себе'),
        ),
    ]
